# Site settings
title: Miran Mirza
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Miran Mirza, Software Developer and fourth year student at Carleton University
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: MiranMirza
github_username:  MiranMirza

#description: I got reprogrammed by a rogue AI and now I'm totally cray

# Build settings
markdown: kramdown
