# Site settings
title: Miran Mirza
email: miran@outlook.com
description: Hi, I'm Miran Mirza, Software Developer and fourth year student at Carleton University
url: "http://miranmirza.com" # the base hostname & protocol for your site
twitter_username: MiranMirza
github_username:  MiranMirza

#description: I got reprogrammed by a rogue AI and now I'm totally cray

# Build settings
markdown: kramdown
